config/routes.rb
Rails.application.routes.draw do
  # get 'favorites/create'

  # get 'favorites/destroy'

  get 'users/index'

  get 'users/show'
  
  resources :favorites, only: [:create, :destroy]

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, :only => [:index, :show]
  
  get '/instaclone_contents', to: 'instaclone_contents#index'
  
  resources :instaclone_contents do
    collection do
      post :confirm
    end
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  root :to => 'instaclone_contents#index'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :instaclone_content
end

app/models/instaclone_content.rb
class InstacloneContent < ApplicationRecord
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  
  validates :title, presence: true
  validates :content, presence: true
  
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :confirmable,
         :validatable, :omniauthable, omniauth_providers: %i(google facebook)
         
  has_many :instaclone_contents, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_instaclone_contents, through: :favorites, source: :instaclone_content
  
  mount_uploader :image_url, ImageUploader
  
  def self.create_unique_string
    SecureRandom.uuid
  end
  
  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)
    unless user
      user = User.new(email: auth.info.email,
        provider: auth.provider,
        uid: auth.uid,
        password: Devise.friendly_token[0, 20],
        )
    end
    user.save
    user
  end
  
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(provider: auth.provider,
        uid: auth.uid,
        email: "#{auth.uid}-#{auth.provider}@example.com",
        password: Devise.friendly_token[0, 20]
        )
    end
    user.save
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  #変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
  PERMISSIBLE_ATTRIBUTES = %i(name image image_cache)

  protected

  #deviseのストロングパラメーターにカラム追加するメソッドを定義
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
    devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    current_user.favorites.create(instaclone_content_id: params[:instaclone_content_id])
    #redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
    redirect_to instaclone_contents_url
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    #redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
    redirect_to instaclone_contents_url
  end
end

app/controllers/instaclone_contents_controller.rb
class InstacloneContentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_instaclone_content, only: [:show, :edit, :update, :destroy]

  def index
      @instaclone_contents = InstacloneContent.all
      @users = User.all
      
  end
  
  def new
    if params[:back]
      @instaclone_content = InstacloneContent.new(instaclone_contents_params)
      @instaclone_content.image.retrieve_from_cache! params[:cache][:image]
    else
      @instaclone_content = InstacloneContent.new
    end
    
  end  

  
  def create
    @instaclone_content = InstacloneContent.new(instaclone_contents_params)
    if !params[:cache].nil? && params[:cache][:image].present?
      @instaclone_content.image.retrieve_from_cache!  params[:cache][:image]
    end
    # @instaclone_content.user_id = current_user.id
    @instaclone_content.user = current_user
    
    if @instaclone_content.save
      InstacloneContentsMailer.instaclone_contents_mail(@instaclone_content).deliver
      redirect_to instaclone_contents_path, notice: "投稿しました！"
      #NoticeMailer.sendmail_instaclone_content(@instaclone_content).deliver
    else
      render 'new'
    end
  end

  def edit
    @instaclone_content = InstacloneContent.find(params[:id])
  end
  
  def update
    if @instaclone_content.update(instaclone_contents_params)
      # 編集したことをメールで通知します
      InstacloneContentsMailer.instaclone_contents_mail(@instaclone_content).deliver
      redirect_to instaclone_contents_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    # @instaclone_content = InstacloneContent.find(params[:id])
    @instaclone_content.destroy
    InstacloneContentsMailer.instaclone_contents_mail(@instaclone_content).deliver
    redirect_to instaclone_contents_path, notice: "投稿を削除しました！"
  end

  def confirm
    @instaclone_content = InstacloneContent.new(instaclone_contents_params)
    @instaclone_content.user = current_user
    if @instaclone_content.invalid?
      render:new
    end
  end

 private
  def instaclone_contents_params
    params.require(:instaclone_content).permit(:title, :image, :image_cache, :content, :user_id)
  end
  
  def set_instaclone_content
   @instaclone_content = InstacloneContent.find(params[:id])
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google
    @user = User.find_for_google(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "google") if is_navigational_format?
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
  
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash={})
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @favorite_instaclone_contents = @user.favorite_instaclone_contents
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_img(user)
    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: user.name)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/instaclone_contents_helper.rb
module InstacloneContentsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_instaclone_contents_path
    elsif action_name == 'edit'
      instaclone_content_path
    end
  end
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/instaclone_contents/_form.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(@instaclone_content, url: choose_new_or_edit) do |f| %>

<%#= form_for(@instaclone_content, url:confirm_instaclone_contents_path) do |f| %>

  <% if @instaclone_content.errors.any? %>
    <div id="error_explanation">
      <h2><%= @instaclone_content.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @instaclone_content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :タイトル %><br>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :画像 %><br>
    <%= image_tag(@instaclone_content.image.url) if @instaclone_content.image.url %>
    <%= f.file_field :image, id: :instaclone_content_image %>
    <%= f.hidden_field :image_cache %>
  </div>
  
  <div class="field">
    <%= f.label :コメント %><br>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to "投稿一覧画面にもどる", instaclone_contents_path %>

app/views/instaclone_contents/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

   <h3>以下の内容で、送信する。</h3>
    <%= form_for(@instaclone_content, url: instaclone_contents_path) do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :image %>
      <%= f.hidden_field :content %>
      <p>タイトル:<%= @instaclone_content.title %></p>
      
      <p>画像:<%= image_tag(@instaclone_content.image) %>
      <%= hidden_field_tag :"cache[image]",@instaclone_content.image.cache_name %>
      
      <p>コメント:<%= @instaclone_content.content %></p>
      <%= f.submit "登録", class: 'btn btn-primary btn-block' %>
    
   <% end %>
      
    <%= form_for(@instaclone_content, url: new_instaclone_content_path, method: 'get') do |f| %>
      <%= f.hidden_field :title %>
      <%= hidden_field_tag :"cache[image]",@instaclone_content.image.cache_name %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/instaclone_contents/edit.html.erb
 <h2>投稿を編集する</h2>

 <%= render 'form' %>

app/views/instaclone_contents/index.html.erb
<div class="body">
  <p class="flash"><%= notice %><%= alert %></p>
  <%= image_tag 'instaclone_main.jpg' %>
</div>


<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <button type="button" class="btn btn-primary btn-lg"><%= link_to "投稿する", new_instaclone_content_path, class: 'btn btn-sm btn-default' %></button>

    <% @instaclone_contents.each do |instaclone_content| %>
    
　　　<div style="background-color:#A9D0F5;color:#ffffff">タイトル</div>

      <div class="row">
        <h4><strong><%= instaclone_content.title %></strong></h4>
　　　  <div style="background-color:#a9a9a9;color:#ffffff">画像</div>


        <p><%= image_tag(instaclone_content.image)  %></p>
        <%#= hidden_field_tag :"cache[image]", @instaclone_content.image.cache_name %>


　  　　<div style="background-color:#a9a9a9;color:#ffffff">コメント</div>

        <p><%= instaclone_content.content %></p>

　  　　<div style="background-color:#a9a9a9;color:#ffffff">投稿者</div>

        <p>
        <%= instaclone_content.user.name if instaclone_content.user %></p>
      
        <% if instaclone_content.user_id == current_user.id %>
          <button type="button" class="btn btn-primary btn-lg"><%= link_to "編集", edit_instaclone_content_path(instaclone_content.id), class: 'btn btn-sm btn-success' %></button>
          <button type="button" class="btn btn-primary btn-lg"><%= link_to "削除", instaclone_content_path(instaclone_content.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-sm btn-danger' %></button>
        <% else %>
          <% if current_user.favorites.find_by(instaclone_content_id: instaclone_content.id).present? %>
            <button type="button" class="btn btn-primary btn-lg"><%= link_to "お気に入り解除", favorite_path(current_user.favorites.find_by(instaclone_content_id: instaclone_content.id).id), method: :delete, class: 'btn btn-sm btn-danger' %></button>
          <% else %>
            <button type="button" class="btn btn-primary btn-lg"><%= link_to "お気に入り登録", favorites_path(instaclone_content_id: instaclone_content.id), method: :post, class: 'btn btn-sm btn-success' %></button>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/instaclone_contents/new.html.erb
 <h2>投稿を作成する</h2>

 <%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
　  <div class="header">
      <% if user_signed_in? %>
        <li><%= link_to 'マイページ', user_path(current_user.id) %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path  %></li>
        <li><%= link_to 'サインアップ', new_user_registration_path %></li>
      <% end %>
      <li><%= link_to "投稿一覧", instaclone_contents_path %></li>
    </div>

    <%= yield %>

  </body>

  <footer class="footer">
    <p align = center>NTTPC 柴田　喜匡　が勉強中です</p>
    <p align = center>©2018 Copy-Free</p>
  </footer>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<p><div style="background-color:#a9a9a9;color:#ffffff">お気に入りの一覧</div></p>

<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <% @favorite_instaclone_contents.each do |instaclone_content| %>
　　　<div style="background-color:#A9D0F5;color:#ffffff">タイトル</div>
      
      <div class="row">
        <h4><strong><%= instaclone_content.title %></strong></h4>
　　    
　　    <div style="background-color:#a9a9a9;color:#ffffff">画像</div>
        <p><%= image_tag(instaclone_content.image)  %></p>

        <div style="background-color:#a9a9a9;color:#ffffff">コメント</div>
        <p><%= instaclone_content.content %></p>

　　　  <div style="background-color:#a9a9a9;color:#ffffff">投稿者</div>
        <p><%= instaclone_content.user.name if instaclone_content.user %></p>
      </div>
    <% end %>
  </div>
</div>